package liveresultsclient.entity;
// Generated May 8, 2016 11:03:12 AM by Hibernate Tools 3.6.0



/**
 * Serie generated by hbm2java
 */
public class Serie  implements java.io.Serializable {


     private Integer id;
     private Onderdelen onderdelen;
     private Img img;
     private String wind;
     private int serieNummer;

    public Serie() {
    }

	
    public Serie(Onderdelen onderdelen, int serieNummer) {
        this.onderdelen = onderdelen;
        this.serieNummer = serieNummer;
    }
    public Serie(Onderdelen onderdelen, Img img, String wind, int serieNummer) {
       this.onderdelen = onderdelen;
       this.img = img;
       this.wind = wind;
       this.serieNummer = serieNummer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Onderdelen getOnderdelen() {
        return this.onderdelen;
    }
    
    public void setOnderdelen(Onderdelen onderdelen) {
        this.onderdelen = onderdelen;
    }
    public Img getImg() {
        return this.img;
    }
    
    public void setImg(Img img) {
        this.img = img;
    }
    public String getWind() {
        return this.wind;
    }
    
    public void setWind(String wind) {
        this.wind = wind;
    }
    public int getSerieNummer() {
        return this.serieNummer;
    }
    
    public void setSerieNummer(int serieNummer) {
        this.serieNummer = serieNummer;
    }




}


