package liveresultsclient.entity;
// Generated Sep 19, 2016 7:42:13 PM by Hibernate Tools 4.3.1

import java.util.regex.Matcher;




/**
 * Sislane generated by hbm2java
 */
public class Sislane  implements java.io.Serializable {


     private int idSislane;
     private Sisresult sisresult;
     private Integer place;
     private int lane;
     private int signalValue;
     private Double reactionTime;
     private boolean falseStart;
     
    public Sislane() {
        
    }
     
    public Sislane(Matcher m,Sisresult result) {
        //8  OK   012  0.199 
        setSisresult(result);
        System.out.println(m.group(0));
        place = tryParse(m.group(1));
        lane = tryParse(m.group(2));
        falseStart = m.group(3).contains("FLASE");
        signalValue = tryParse(m.group(4));
        if (!m.group(5).contains("-")) {
            reactionTime = Double.parseDouble(m.group(5).replace(",", "."));
            falseStart=reactionTime<0.1;
        }
    }

    public Integer tryParse(Object obj) {
        Integer retVal;
        try {
            retVal = Integer.parseInt(((String) obj).trim());
        } catch (NumberFormatException nfe) {
            retVal = 0; // or null if that is your preference
        }
        return retVal;
    }

	
    public Sislane(int idSislane, int lane, int signalValue, boolean falseStart) {
        this.idSislane = idSislane;
        this.lane = lane;
        this.signalValue = signalValue;
        this.falseStart = falseStart;
    }
    public Sislane(int idSislane, Sisresult sisresult, Integer place, int lane, int signalValue, Double reactionTime, boolean falseStart) {
       this.idSislane = idSislane;
       this.sisresult = sisresult;
       this.place = place;
       this.lane = lane;
       this.signalValue = signalValue;
       this.reactionTime = reactionTime;
       this.falseStart = falseStart;
    }
   
    public int getIdSislane() {
        return this.idSislane;
    }
    
    public void setIdSislane(int idSislane) {
        this.idSislane = idSislane;
    }
    public Sisresult getSisresult() {
        return this.sisresult;
    }
    
    public void setSisresult(Sisresult sisresult) {
        this.sisresult = sisresult;
    }
    public Integer getPlace() {
        return this.place;
    }
    
    public void setPlace(Integer place) {
        this.place = place;
    }
    public int getLane() {
        return this.lane;
    }
    
    public void setLane(int lane) {
        this.lane = lane;
    }
    public int getSignalValue() {
        return this.signalValue;
    }
    
    public void setSignalValue(int signalValue) {
        this.signalValue = signalValue;
    }
    public Double getReactionTime() {
        return this.reactionTime;
    }
    
    public void setReactionTime(Double reactionTime) {
        this.reactionTime = reactionTime;
    }
    public boolean isFalseStart() {
        return this.falseStart;
    }
    
    public void setFalseStart(boolean falseStart) {
        this.falseStart = falseStart;
    }




}


