package liveresultsclient.entity;
// Generated May 8, 2016 11:03:12 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Wedstrijden generated by hbm2java
 */
public class Wedstrijden  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private String locatie;
     private Date datum;
     private String youtubeLink;
     private Boolean public_;
     private Set onderdelens = new HashSet(0);
     private Set atletens = new HashSet(0);
     private Set atletiekNus = new HashSet(0);
     private Set sisresults = new HashSet(0);

    public Wedstrijden() {
    }

	
    public Wedstrijden(String naam) {
        this.naam = naam;
    }
    public Wedstrijden(String naam, String locatie, Date datum, String youtubeLink, Boolean public_, Set onderdelens, Set atletens, Set atletiekNus) {
       this.naam = naam;
       this.locatie = locatie;
       this.datum = datum;
       this.youtubeLink = youtubeLink;
       this.public_ = public_;
       this.onderdelens = onderdelens;
       this.atletens = atletens;
       this.atletiekNus = atletiekNus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getLocatie() {
        return this.locatie;
    }
    
    public void setLocatie(String locatie) {
        this.locatie = locatie;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public String getYoutubeLink() {
        return this.youtubeLink;
    }
    
    public void setYoutubeLink(String youtubeLink) {
        this.youtubeLink = youtubeLink;
    }
    public Boolean getPublic_() {
        return this.public_;
    }
    
    public void setPublic_(Boolean public_) {
        this.public_ = public_;
    }
    public Set getOnderdelens() {
        return this.onderdelens;
    }
    
    public void setOnderdelens(Set onderdelens) {
        this.onderdelens = onderdelens;
    }
    public Set getAtletens() {
        return this.atletens;
    }
    
    public void setAtletens(Set atletens) {
        this.atletens = atletens;
    }
    public Set getAtletiekNus() {
        return this.atletiekNus;
    }
    
    public void setAtletiekNus(Set atletiekNus) {
        this.atletiekNus = atletiekNus;
    }
    
    public Set getSisresults() {
        return this.sisresults;
    }
    
    public void setSisresults(Set sisresults) {
        this.sisresults = sisresults;
    }




}


