/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.phanos.testwedstrijdrunner.gui;

import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import liveresultsclient.entity.Sisresult;
import liveresultsclient.entity.Wedstrijden;
import nl.phanos.testwedstrijdrunner.utils.HibernateSessionHandler;
import nl.phanos.testwedstrijdrunner.utils.savingHandler;

/**
 *
 * @author woutermkievit
 */
public class MainWindow extends javax.swing.JFrame {

    public static MainWindow mainObj;
    public Wedstrijden wedstrijd;
    public boolean test = false;

    public javax.swing.JTextPane jTextPane1 = new JTextPane();

    private javax.swing.JScrollPane jScrollPane4 = new JScrollPane();

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        jScrollPane4.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        HibernateSessionHandler sessionHandler = HibernateSessionHandler.get();
        List<Wedstrijden> resultList = sessionHandler.executeHQLQuery("from Wedstrijden");
        Collections.sort(resultList, new Comparator<Wedstrijden>() {
                @Override
                public int compare(Wedstrijden a, Wedstrijden b) {
                    // -1 - less than, 1 - greater than, 0 - equal, all inversed for descending
                    return -1*a.getDatum().compareTo(b.getDatum());
                }
            });
        Object[] possibilities = resultList.stream().map(x->x.getNaam()).toArray();
        String response = (String) JOptionPane.showInputDialog(
                this,
                "welke wedstrijd is nu?",
                "Wedstrijd Dialog",
                JOptionPane.PLAIN_MESSAGE,
                null,
                possibilities,
                possibilities[0]);

//If a string was returned, say so.
        int chosen = Arrays.asList(possibilities).indexOf(response);
        if(chosen>=0){
            this.wedstrijd=resultList.get(chosen);
            Sisresult.startHandler();
            savingHandler saver=new savingHandler();
            saver.start();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainObj = new MainWindow();
                mainObj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
