package nl.phanos.testwedstrijdrunner.entity;
// Generated May 8, 2016 11:03:12 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Img generated by hbm2java
 */
public class Img  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String type;
     private int size;
     private byte[] content;
     private String uploadDate;
     private Set series = new HashSet(0);

    public Img() {
    }

	
    public Img(String name, String type, int size, byte[] content, String uploadDate) {
        this.name = name;
        this.type = type;
        this.size = size;
        this.content = content;
        this.uploadDate = uploadDate;
    }
    public Img(String name, String type, int size, byte[] content, String uploadDate, Set series) {
       this.name = name;
       this.type = type;
       this.size = size;
       this.content = content;
       this.uploadDate = uploadDate;
       this.series = series;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getSize() {
        return this.size;
    }
    
    public void setSize(int size) {
        this.size = size;
    }
    public byte[] getContent() {
        return this.content;
    }
    
    public void setContent(byte[] content) {
        this.content = content;
    }
    public String getUploadDate() {
        return this.uploadDate;
    }
    
    public void setUploadDate(String uploadDate) {
        this.uploadDate = uploadDate;
    }
    public Set getSeries() {
        return this.series;
    }
    
    public void setSeries(Set series) {
        this.series = series;
    }




}


