package nl.phanos.testwedstrijdrunner.entity;
// Generated May 8, 2016 11:03:12 AM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import nl.phanos.testwedstrijdrunner.utils.HibernateSessionHandler;
import org.hibernate.Session;

/**
 * Onderdelen generated by hbm2java
 */
public class Onderdelen implements java.io.Serializable {

    private Integer id;
    private Wedstrijden wedstrijden;
    private String filter;
    private String onderdeel;
    private String opmerking;
    private String raceName;
    private String displayName;
    private String categorie;
    private Date tijd;
    private Integer externalId;
    private Set series = new HashSet(0);
    private Set uitslagens = new HashSet(0);
    private Set startLijstens = new HashSet(0);

    public Onderdelen() {
    }

    public Onderdelen(Wedstrijden wedstrijden, String onderdeel, String opmerking) {
        this.wedstrijden = wedstrijden;
        this.onderdeel = onderdeel;
        this.opmerking = opmerking;
    }

    public Onderdelen(Wedstrijden wedstrijden, String filter, String onderdeel, String opmerking, String raceName, String displayName, String categorie, Date tijd, Integer externalId, Set series, Set uitslagens, Set startLijstens) {
        this.wedstrijden = wedstrijden;
        this.filter = filter;
        this.onderdeel = onderdeel;
        this.opmerking = opmerking;
        this.raceName = raceName;
        this.displayName = displayName;
        this.categorie = categorie;
        this.tijd = tijd;
        this.externalId = externalId;
        this.series = series;
        this.uitslagens = uitslagens;
        this.startLijstens = startLijstens;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Wedstrijden getWedstrijden() {
        return this.wedstrijden;
    }

    public void setWedstrijden(Wedstrijden wedstrijden) {
        this.wedstrijden = wedstrijden;
    }

    public String getFilter() {
        return this.filter;
    }

    public void setFilter(String filter) {
        this.filter = filter;
    }

    public String getOnderdeel() {
        return this.onderdeel;
    }

    public void setOnderdeel(String onderdeel) {
        this.onderdeel = onderdeel;
    }

    public String getOpmerking() {
        return this.opmerking;
    }

    public void setOpmerking(String opmerking) {
        this.opmerking = opmerking;
    }

    public String getRaceName() {
        return this.raceName;
    }

    public void setRaceName(String raceName) {
        this.raceName = raceName;
    }

    public String getDisplayName() {
        return this.displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getCategorie() {
        return this.categorie;
    }

    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }

    public Date getTijd() {
        return this.tijd;
    }

    public void setTijd(Date tijd) {
        this.tijd = tijd;
    }

    public Integer getExternalId() {
        return this.externalId;
    }

    public void setExternalId(Integer externalId) {
        this.externalId = externalId;
    }

    public Set getSeries() {
        return this.series;
    }

    public void setSeries(Set series) {
        this.series = series;
    }

    public Set getUitslagens() {
        return this.uitslagens;
    }    

    public void setUitslagens(Set uitslagens) {
        this.uitslagens = uitslagens;
    }

    public Set getStartLijstens() {
        return this.startLijstens;
    }

    public void setStartLijstens(Set startLijstens) {
        this.startLijstens = startLijstens;
    }

    public boolean getReady() {
        Iterator iter = startLijstens.iterator();
        while (iter.hasNext()) {
            StartLijsten startlijst=(StartLijsten)iter.next();
            if(startlijst.getBaan()<=0){
                return false;
            }
        }
        return true;
    }
    
    public void updateStartLijsten(){
        HibernateSessionHandler sessionHandler = HibernateSessionHandler.get();
        sessionHandler.update(this);
    }

}
