package nl.phanos.testwedstrijdrunner.entity;
// Generated May 8, 2016 11:03:12 AM by Hibernate Tools 3.6.0



/**
 * StartLijsten generated by hbm2java
 */
public class StartLijsten  implements java.io.Serializable {


     private Integer id;
     private Onderdelen onderdelen;
     private Atleten atleten;
     private int serie;
     private int baan;
     private String qpresatie;
     private boolean nextRound;

    public StartLijsten() {
    }

	
    public StartLijsten(Onderdelen onderdelen, Atleten atleten, int serie, int baan, boolean nextRound) {
        this.onderdelen = onderdelen;
        this.atleten = atleten;
        this.serie = serie;
        this.baan = baan;
        this.nextRound = nextRound;
    }
    public StartLijsten(Onderdelen onderdelen, Atleten atleten, int serie, int baan, String qpresatie, boolean nextRound) {
       this.onderdelen = onderdelen;
       this.atleten = atleten;
       this.serie = serie;
       this.baan = baan;
       this.qpresatie = qpresatie;
       this.nextRound = nextRound;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Onderdelen getOnderdelen() {
        return this.onderdelen;
    }
    
    public void setOnderdelen(Onderdelen onderdelen) {
        this.onderdelen = onderdelen;
    }
    public Atleten getAtleten() {
        return this.atleten;
    }
    
    public void setAtleten(Atleten atleten) {
        this.atleten = atleten;
    }
    public int getSerie() {
        return this.serie;
    }
    
    public void setSerie(int serie) {
        this.serie = serie;
    }
    public int getBaan() {
        return this.baan;
    }
    
    public void setBaan(int baan) {
        this.baan = baan;
    }
    public String getQpresatie() {
        return this.qpresatie;
    }
    
    public void setQpresatie(String qpresatie) {
        this.qpresatie = qpresatie;
    }
    public boolean isNextRound() {
        return this.nextRound;
    }
    
    public void setNextRound(boolean nextRound) {
        this.nextRound = nextRound;
    }




}


